apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecom-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - 'until nc -z -v -w3 postgres-service 5432; do echo "Dang cho PostgreSQL..."; sleep 3; done;'
      containers:
        - name: backend
          image: harbor.lab.local/spring-testing/spring-testing-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/ecom_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgrespassword"
            # Khai báo trực tiếp Driver & Dialect để tránh lỗi metadata
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ecom-dev
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080