spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/ecom_db
spring.datasource.username=postgres
spring.datasource.password=gbao4132

# Tự động tạo/cập nhật bảng theo Entity trong code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true